language: python

matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          python: "2.7"

        - os: linux
          python: "3.5"

        - os: linux
          python: "3.6"

        # Use generic language for osx
        - os: osx
          language: generic
          python: "2.7"

        - os: osx
          language: generic
          python: "3.5"

        - os: osx
          language: generic
          python: "3.6"

        # Use sh language for windows
        - os: windows
          language: sh
          python: "2.7"
          before_install:
            - choco install python --version 2.7.11
            - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"

        - os: windows
          language: sh
          python: "3.5"
          before_install:
            - choco install python --version 3.5.4
            - export PATH="/c/Python35:/c/Python35/Scripts:$PATH"

        - os: windows
          language: sh
          python: "3.6"
          before_install:
            - choco install python --version 3.6.7
            - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$TRAVIS_PYTHON_VERSION" = "2.7" ] ; then   brew install python2.7 && virtualenv venv -p python2.7 && source venv/bin/activate; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$TRAVIS_PYTHON_VERSION" = "3.5" ] ; then   brew install python3.5 && virtualenv venv -p python3.5 && source venv/bin/activate; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$TRAVIS_PYTHON_VERSION" = "3.6" ] ; then   brew install python3.6 && virtualenv venv -p python3.6 && source venv/bin/activate; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ] && [ "$TRAVIS_PYTHON_VERSION" = "2.7" ] ; then  virtualenv $HOME/venv && source $HOME/venv/Scripts/activate; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ] && [ "$TRAVIS_PYTHON_VERSION" = "3.5" ] ; then  virtualenv $HOME/venv && source $HOME/venv/Scripts/activate; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ] && [ "$TRAVIS_PYTHON_VERSION" = "3.6" ] ; then  virtualenv $HOME/venv && source $HOME/venv/Scripts/activate; fi

install:
  - pip install coverage
  - pip install codecov
  - pip install -U pytest
  - pip install --upgrade setuptools wheel

script:
  - python setup.py install
  - cd tests
  - pip list
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_PYTHON_VERSION" = "3.6" ] ; then coverage run -m --source=../mlbox/ pytest; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_PYTHON_VERSION" != "3.6" ] ; then pytest; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then pytest; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ] ; then pytest; fi

after_success:
  - codecov

deploy:
  provider: pypi
  user: AxeldeRomblay
  password:
    secure: YiApWm2gnE2SiBQQZ4gbWEJrFl+Jo381e07viF9Lgo30+mjnCEpMilAZpCl9MuzslOkXyFCv/U9JNnj9+yGtMcxJQE+82E3eoqupgoMQeGZuWIMN9cRNemxZWgOAwrzslfqEYWvMVdNzIayFYAw6HUgmNI5sHiefX2JjFA7Y0MYlL0SZBjeqUESqpjTHIS0nRTCKpv77XKo/SASJsqkpYg8OgnYgKWKvxpols/bZDwmAwy2j0izuyNAY9ASJx5awg9x/bJnn7IzvO8w+j/iQTQjs5CIa1NBW77Naqplxk1rlivIO3+3rT4QJG+xRacJHa1vLInATCcUVpbhzk/NbOPUxLXpxX6XUPDhUysR1sQbaYBbBOdLOnTAmKBv5WozLzXDUxO/3xwUNUB5+JhMikjOWiwA6Q9pJ7q/nsDMRoTcXrjN/jqMDMQ+CU7h7QBIZFoekDO2hEmWRkcgndbgzPcaTmX8AnjoZCvayYvdge47199feXkTUv+Gx68kInYuj+p3m6He36tJegCnsiAdc2eOzbPswt7/KVBbvbIfRaRj+5LtH69ozn1xpEJJOisiJnF9y0ysB00U4B4bE1kGGmxQeMI6f8Gp33wzvYYUrmB+5AESBzr7Mk4Yfc0Y36vA6NilIj7bK4WmTsWkCmmzazGOwgKi1zWC51W/SjNXyWkc=
