version: 1.0.{build}

environment:
  matrix:
    - PYTHON: "C:/Python36-x64"
      PYTHON_VERSION: 3.6
      MINICONDA: "C:/Miniconda36-x64"
  
# command to install dependencies
install:
  - pip install codecov
  - pip install --upgrade pip setuptools wheel  
  - pip install --only-binary all -r python-package/requirements.txt
  
# command to run tests
script:
  - cd python-package
  - python setup.py install
  - cd ../tests
  - coverage run test_mlbox.py
